### ISSUE TITLE
Can refer key vault secret via variable group?

### ISSUE THREAD

**Issue by yoonghan** [yoonghan/yoonghan#23]

**Comment by yoonghan** [comment]
Yes just need this toggle "Link secrets from an Azure key vault as variables"
https://learn.microsoft.com/en-us/azure/devops/pipelines/library/link-variable-groups-to-key-vaults?view=azure-devops
Steps:
1. Create variable group -> check toggle link -> add subscription and key vault id -> define secrets to read.
2. Then can directly refer to the defined secret on 1. E.g. if secret in kv is 'acr-secret', the pipeline just put 'acr-secret'. But if both are duplicated, then how?
https://microsoftlearning.github.io/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/Instructions/Labs/AZ400_M04_L10_Integrate_Azure_Key_Vault_with_Azure_DevOps.html

You can even write back the secret. Oh.
https://learn.microsoft.com/en-us/azure/devops/pipelines/process/set-secret-variables?view=azure-devops&tabs=yaml%2Cbash

**Comment by yoonghan** [comment]
Variable groups if different but have same name, the last one overrides the first one. To over come

Option 1: Rewrite (this can be global or in job) and override it

```yaml
    variables:
      - group: VariableGroupA
        - name: myVarFromGroupA
           value: $[variables.myVar]   # Save original to distinct name
     - group: VariableGroupB
       - name: myVarFromGroupB
          value: $[variables.myVar]   # This overrides variables.myVar
```

Option 2: Defines which variable to use

```yaml
  jobs:
    - job: Example
       variables:
         - group: ${{ parameters.variableGroup }} # either in template or just hardcode the variableGroup name
```

**Comment by yoonghan** [comment]
You can use Variable group for
- approval and check.
- pipeline permission

Github and Devops use environment for checks. Just a note.

```yaml
  - stage: Deploy
    displayName: Deploy to an Azure Web App
    jobs:
    - deployment: Deploy
      environment: approval
```

```yaml
  deploy:
    runs-on: ubuntu-latest
    needs: buildandtest
    environment:
      name: 'Development'
    steps:
```

**Comment by yoonghan** [comment]
Now under variable groups there is a "Approve and Checks". It controls within business hours an approval is required before the secret can be used.

```yaml
  variables:
    - group: ProdSecrets

  stages:
  - stage: DeployProd
    jobs:
      - job: Deploy
        steps:
          - script: echo "Deploying using production secrets"
```
