### ISSUE TITLE
Devops Repository resource

### ISSUE THREAD

**Issue by yoonghan** [yoonghan/yoonghan#26]
Refers to repository even for external git libraries, the code looks like

```yaml
resources:
  repositories:
  - repository: common
    type: github #note githubenterprise is seperate, it has extra security
    name: Contoso/CommonTools
    endpoint: MyContosoServiceConnection
```

But with this, batch cannot work. Batch is batching commits that prevents concurrent jobs to run in pipeline with trigger.

```yaml
trigger:
  batch: true # per branch batching
  branches:
    include:
    - '*' # Must enclose in '' since * is a reserved YAML character
    exclude:
    - main
```
